=== Flaredashboard/tso-registry/src/singleProviderSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://github.com/Flaredashboard/tso-registry/src/singleProviderSchema.json",
  "title": "Tso provider static data schema",
  "description": "Schema for single tso data",
  "definitions": {
    "baseTso": {
      "type": "object",
      "required": ["chainId", "address", "epoch"],
      "properties": {
        "address": {
          "type": "string",
          "description": "The checksummed address of the FTSO provider on the specified chain ID",
          "pattern": "^0x[a-fA-F0-9]{40}$",
          "examples": ["0x7d0F24d863961e7C51C28A3eC092C96239FBD05e"]
        },
        "epoch": {
          "type": "number",
          "description": "The first epoch where the TSO began submitting",
          "minimum": 0,
          "examples": [10]
        },
        "claim_addresses": {
          "type": "array",
          "items": {
            "type": "string",
            "pattern": "^0x[a-fA-F0-9]{40}$"
          },
          "description": "The addresses that the TSO provider is claiming the rewards to",
          "examples": [
            [
              "0x7d0F24d863961e7C51C28A3eC092C96239FBD05e",
              "0x7d0F24d863961e7C51C28A3eC092C96239dd00ff"
            ]
          ]
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the TSO provider",
      "minLength": 2,
      "maxLength": 32,
      "pattern": "^[ \\w.'+\\-%/À-ÖØ-öø-ÿ:&\\[\\]\\(\\)]+$",
      "examples": ["Cool Oracle Name"]
    },
    "website": {
      "type": "string",
      "description": "A URI to the TSO provider website. Must use HTTPS",
      "maxLength": 150,
      "pattern": "^https://[A-Za-z0-9/#.-]*[^/]$",
      "examples": ["https://github.com/"]
    },
    "twitter": {
      "type": "string",
      "description": "A URI to the TSO provider twitter. Must use HTTPS",
      "maxLength": 150,
      "pattern": "^https://twitter.com/[A-Za-z0-9/_]*[^/]$",
      "examples": ["https://twitter.com/dashboard_flare/"]
    },
    "members": {
      "type": "number",
      "description": "Number of members running the TSO",
      "minimum": 1,
      "examples": [3]
    },
    "country": {
      "type": "string",
      "description": "Country where the headquarters are located",
      "maxLength": 20,
      "examples": ["Australia"]
    },
    "nodes": {
      "type": "number",
      "description": "Number of nodes that the team is running on both chains",
      "minimum": 0,
      "examples": [4]
    },
    "categories": {
      "type": "array",
      "description": "Categories where the TSO is building their products",
      "items": {
        "type": "string",
        "enum": ["NFT", "DeFi", "Metaverse", "Wallets", "Gaming", "Utilities"]
      },
      "examples": ["NFT"]
    },
    "description": {
      "type": "string",
      "description": "The description of the TSO provider",
      "minLength": 10,
      "maxLength": 200,
      "pattern": "^[ \\w.'+\\-%/À-ÖØ-öø-ÿ:&\\[\\]\\(\\)]+",
      "examples": ["description of the cool oracle"]
    },
    "logoURI": {
      "type": "string",
      "description": "A content URL for this TSO provider logo asset",
      "pattern": "^(ipfs:|https:)//[A-Za-z0-9/#.-]*[^/]$",
      "examples": ["ipfs://QmQqeBKAubYHyhJZ7QQzfDmWkxhrnCFmrQKxha4cwKTouC"]
    },
    "signature": {
      "type": "string",
      "description": "The public signature of the provider",
      "pattern": "^[a-fA-F0-9]*$",
      "examples": [
        "123456789123456789123456789123456789123456789123456789123456789123456789"
      ]
    },
    "general": {
      "type": "string",
      "description": "The general information of the TSO provider (e.g. long description of TSO)",
      "minLength": 10,
      "maxLength": 5000,
      "examples": ["general information about the cool oracle"]
    },
    "infrastructure": {
      "type": "string",
      "description": "The information about the infrastructure of the TSO provider",
      "minLength": 10,
      "maxLength": 5000,
      "examples": ["infrastructure information about the cool oracle"]
    },
    "safeguards": {
      "type": "string",
      "description": "The information about the safeguards of the TSO provider",
      "minLength": 10,
      "maxLength": 5000,
      "examples": ["safeguards information about the cool oracle"]
    },
    "availability": {
      "type": "string",
      "description": "The information about the availability of the TSO provider",
      "minLength": 10,
      "maxLength": 5000,
      "examples": ["availability information about the cool oracle"]
    },
    "tooling": {
      "type": "string",
      "description": "The information about the tooling of the TSO provider",
      "minLength": 10,
      "maxLength": 5000,
      "examples": ["tooling information about the cool oracle"]
    },
    "products": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^https://[A-Za-z0-9/#.-]*[^/]$"
      },
      "description": "URLs of the products that the TSO provider has built. Must use HTTPS",
      "examples": [["https://flaredashboard.io/"]]
    },
    "stso_info": {
      "allOf": [
        {
          "$ref": "#/definitions/baseTso"
        },
        {
          "type": "object",
          "properties": {
            "chainId": {
              "type": "integer",
              "description": "The chain ID (14: Flare, 19: Songbird) where this TSO provider is submitting prices",
              "enum": [19],
              "examples": [19]
            }
          }
        }
      ]
    },
    "ftso_info": {
      "allOf": [
        {
          "$ref": "#/definitions/baseTso"
        },
        {
          "type": "object",
          "properties": {
            "chainId": {
              "type": "integer",
              "description": "The chain ID (14: Flare, 19: Songbird) where this TSO provider is submitting prices",
              "enum": [14],
              "examples": [14]
            }
          }
        }
      ]
    }
  },
  "anyOf": [
    {
      "required": ["stso_info"]
    },
    {
      "required": ["ftso_info"]
    }
  ],
  "required": ["name", "description", "website", "logoURI", "members", "country", "nodes", "categories"],
  "additionalProperties": false
}

=== Flaredashboard/tso-registry/providers/0x1E8F916CE03F4ce86186531a8994d366581Ed4be.json
{
    "name": "Sun-Dara",
    "website": "https://sun-dara.co.uk",
    "twitter": "https://twitter.com/sundaracouk1",
    "description": "We try to operate in the overall, best interest for the network.",
    "general": "We are an independent FTSO, STSO and infrastructure provider to help support the ecosystem grow.",
    "availability": "As time moved on, we should see our availability get better. We are currently upgrading network infrastructure to help with this.",
    "logoURI": "https://sun-dara.co.uk/img/0x1E8F916CE03F4ce86186531a8994d366581Ed4be.png",
    "members": 9,
    "country": "Bangladesh",
    "nodes": 4,
    "categories": [
        "DeFi",
        "Utilities"
    ],
    "ftso_info": {
        "chainId": 14,
        "address": "0x1E8F916CE03F4ce86186531a8994d366581Ed4be",
        "epoch": 1
    },
    "stso_info": {
        "chainId": 19,
        "address": "0x7394923453FC2F606cfb4D0ea1A5438BB8260D08",
        "epoch": 3
    }
}

=== Flaredashboard/tso-registry/providers/0x4990320858AE3528B645C60059281a66C3488888.json
{
  "name": "FTSO AU",
  "website": "https://ftso.au",
  "twitter": "https://twitter.com/ftso_au",
  "description": "Providing value to the Flare ecosystem and it's participants. ",
  "general": "We provide accurate and reliable price feeds to the Songbird & Flare network and a transparent, incentivised, risk-free delegation service. We run observation and validation nodes, as well as underlying chain nodes, to support attestation services. FTSO AU are an active member of the Flare ecosystem.",
  "availability": "We use best in class global data centres, our SLA guarantees a Monthly Uptime Percentage of at least 99.99%. Our pricing data is real-time, accurate and robust.",
  "logoURI": "https://www.ftso.au/img/logo.png",
  "members": 2,
  "country": "Dubai",
  "nodes": 10,
  "categories": ["Utilities"],
  "ftso_info": {
    "chainId": 14,
    "address": "0x4990320858AE3528B645C60059281a66C3488888",
    "epoch": 1
  },
  "stso_info": {
    "chainId": 19,
    "address": "0x499017adb21d6f70480e4e6224cf4144071c1461",
    "epoch": 1
  }
}

=== Flaredashboard/tso-registry/providers/0x9e55a49D251324B1623dc2A81894D1AfBfB8bbdC.json
{
    "name": "FTSOCAN",
    "website": "https://ftsocan.com/",
    "twitter": "https://twitter.com/ftsocan",
    "description": "Start building passive income with FTSO Canada today!",
    "general": "FTSO Canada is your partner to help you build your passive income on the Flare Network, by providing the Flare Network with a fast and efficient price provider. FTSOCAN is also behind the Flare Linux project, a computer environment that makes deploying FLR and SGB nodes really simple on any computer/OS.",
    "availability": "We are a high-availability price provider, and validator, with very constant uptimes of 99.99%+.",
    "logoURI": "https://ftsocan.com/img/logo-dark-2.svg",
    "members": 2,
    "country": "Canada",
    "nodes": 7,
    "categories": [
        "Utilities"
    ],
    "ftso_info": {
        "chainId": 14,
        "address": "0x9e55a49D251324B1623dc2A81894D1AfBfB8bbdC",
        "epoch": 2
    },
    "stso_info": {
        "chainId": 19,
        "address": "0x7C255e428e95bEbc76e944D49D4F460C84b3A3c3",
        "epoch": 40
    }
}

=== Flaredashboard/tso-registry/providers/0xC522E6A633545872f1afc0cdD7b2D96d97E3dE67.json
{
    "name": "4Dads",
    "website": "https://4dads.io",
    "twitter": "https://twitter.com/4DadsFtso",
    "description": "The 4Dads you always see drinking beers in your web3 neighborhood.",
    "general": "4 dads, 13 children. Childhood friends and born and raised in the Midwest. 2 full stack engineers, a real cfo and a mysterious defi dude.. 60+ combined years of software consulting experience ranging from treasury management, healthcare, financial sectors, defense and cleaning fishtanks.",
    "availability": "We're taken.",
    "logoURI": "https://github.com/TowoLabs/ftso-signal-providers/blob/next/assets/0xC522E6A633545872f1afc0cdD7b2D96d97E3dE67.png",
    "members": 4,
    "country": "United States",
    "nodes": 5,
    "categories": [
        "Gaming"
    ],
    "ftso_info": {
        "chainId": 14,
        "address": "0xC522E6A633545872f1afc0cdD7b2D96d97E3dE67",
        "epoch": 1
    },
    "stso_info": {
        "chainId": 19,
        "address": "0x35D73107A089Ac2b3b14a6681D8c408Aab9568D3",
        "epoch": 6
    }
}

=== Flaredashboard/tso-registry/providers/0x9269fb79B098AB314de8A1E2AFb8705678520443.json
{
    "name": "Aureus Ox",
    "website": "https://aureusox.com",
    "description": "Aureus Ox runs a provider service submitting high quality pricing data since epoch 1 on Songbird. We pride ourselves on consistency, resilient data aggregation algorithms, and maintained uptime.",
    "logoURI": "ipfs://QmUsuVT4LQry7EoxynfCk4oes6g3hhgzWS4eQjGSUxbAsC",
    "members": 1,
    "country": "United States",
    "nodes": 3,
    "categories": ["Utilities"],
    "stso_info": {
      "chainId": 19,
      "address": "0x6d323e71e141ce2d7b752313c8a654a9c9d1b377",
      "epoch": 1
    },
    "ftso_info": {
      "chainId": 14,
      "address": "0x9269fb79B098AB314de8A1E2AFb8705678520443",
      "epoch": 1
    },
    "twitter": "https://twitter.com/AureusOx",
    "infrastructure": "Aureus Ox maintains multiple nodes on Songbird + Flare and develops custom tooling to monitor and mitigate any service downtime. We also maintain application services to wrap, delegate and claim on both the Songbird and Flare networks",
    "safeguards": "We implement multiple safegaurds, not limited to stable coin de-pegs",
    "availability": "Aureus Ox has maintained close to ~100% uptime for provider services since conception on Songbird.",
    "tooling": "All tooling is built in house. Wrap, delegate, and claim all from the Aureus Ox dash: https://aureusox.com/dashboard",
    "products": ["https://aureusox.com/dashboard"]
  }
